insert into TB_SERVER_INFO (SERVER_ID, SERVER_NAME, SERVER_IP, LOCATION, DESCRIPT,REG_DATE,REG_USER_ID,MOD_DATE,MOD_USER_ID) values ('SVR_H3_FEMS','SVR_H3_FEMS', '127.0.0.1', 'H3 3F', 'DESC',sysdate,'admin',sysdate,'admin')
insert into TB_SERVER_INFO (SERVER_ID, SERVER_NAME, SERVER_IP, LOCATION, DESCRIPT,REG_DATE,REG_USER_ID,MOD_DATE,MOD_USER_ID) values ('SVR_H4_FEMS','SVR_H4_FEMS', '127.0.0.1', 'H4 3F', 'DESC',sysdate,'admin',sysdate,'admin')


insert into TB_AGENT_INFO (AGENT_ID, AGENT_NAME, AGENT_TYPE, AGENT_KIND, SERVER_ID,REG_DATE,REG_USER_ID,MOD_DATE,MOD_USER_ID) values ('AGT202_001', 'SVR_H3_FEMS_AGT01', 'PLC', 'MODBUS', 'SVR_H3_FEMS', sysdate,'admin',sysdate,'admin')
insert into TB_AGENT_INFO (AGENT_ID, AGENT_NAME, AGENT_TYPE, AGENT_KIND, SERVER_ID,REG_DATE,REG_USER_ID,MOD_DATE,MOD_USER_ID) values ('AGT202_002', 'SVR_H4_FEMS_AGT01', 'PLC', 'MODBUS', 'SVR_H4_FEMS', sysdate,'admin',sysdate,'admin')

