
CREATE TABLE TB_SERVER_INFO ( 
    SERVER_ID VARCHAR(20)   NOT NULL COMMENT '서버 아이디',
    SERVER_NAME VARCHAR(20) NOT NULL COMMENT '서버 명',
    SERVER_IP VARCHAR(10)   NULL     COMMENT '서버 아이피',
    LOCATION VARCHAR(10)    NULL     COMMENT '서버 위치',
    DESCRIPT VARCHAR(200)   NULL     COMMENT '설명',
    REG_DATE DATE           NOT NULL COMMENT '등록 일시',
    REG_USER_ID VARCHAR(20) NOT NULL COMMENT '등록 사용자 아이디',
    MOD_DATE DATE           NULL     COMMENT '수정 일시',
    MOD_USER_ID VARCHAR(20) NULL     COMMENT '수정 사용자 아이디',
    PRIMARY KEY (SERVER_ID)
);


CREATE TABLE TB_POLLING_GROUP_INFO ( 
    POLLING_GROUP_ID VARCHAR(20)        NOT NULL COMMENT '그룹 아이디',
    POLLING_GROUP_NM VARCHAR(10)        NOT NULL COMMENT '그룹 명',
    POLLING_GROUP_TYPE VARCHAR(10)      NOT NULL COMMENT '그룹 TYPE',
    CYCLE VARCHAR(5)                    NOT NULL COMMENT '수집주기',
    SLEEP_TIME VARCHAR(10)              NULL     COMMENT 'SLEEP TIME',
    TAG_PER_THREAD VARCHAR(10)          NULL     COMMENT 'TAG 별 THREAD',
    DESCRIPT VARCHAR(200)               NULL     COMMENT '설명',
    REG_DATE DATE                       NOT NULL COMMENT '등록 일시',
    REG_USER_ID VARCHAR(20)             NOT NULL COMMENT '등록 사용자 아이디',
    MOD_DATE DATE                       NULL     COMMENT '수정 일시',
    MOD_USER_ID VARCHAR(20)             NULL     COMMENT '수정 사용자 아이디',
    PRIMARY KEY (POLLING_GROUP_ID)
);


CREATE TABLE TB_AGENT_INFO ( 
    AGENT_ID VARCHAR(20)    NOT NULL COMMENT '에이전트 ID' ,
    AGENT_NAME VARCHAR(20)  NOT NULL COMMENT '에이전트 명' ,
    AGENT_TYPE VARCHAR(10)  NOT NULL COMMENT '에이전트 타입',
    AGENT_KIND VARCHAR(10)  NOT NULL COMMENT '에이전트 종류',
    POLLING_GROUP_ID VARCHAR(50)    NULL COMMENT '수집 그룹 아이디',
    DESCRIPT VARCHAR(200)   NULL COMMENT '설명',
    SERVER_ID VARCHAR(20)   NOT NULL COMMENT '서버 아이디',
    REG_DATE DATE           NOT NULL COMMENT '등록 일시',
    REG_USER_ID VARCHAR(20) NOT NULL COMMENT '등록 사용자 아이디',
    MOD_DATE DATE           NULL COMMENT '수정 일시',
    MOD_USER_ID VARCHAR(20) NULL COMMENT '수정 사용자 아이디',
    PRIMARY KEY (AGENT_ID)
);


ALTER TABLE TB_AGENT_INFO ADD CONSTRAINT FK_TB_AGENT_INFO_TB_POLLING_GROUP_INFO 
    FOREIGN KEY (POLLING_GROUP_ID) REFERENCES TB_POLLING_GROUP_INFO (POLLING_GROUP_ID)
;

ALTER TABLE TB_AGENT_INFO ADD CONSTRAINT FK_TB_AGENT_INFO_TB_SERVER_INFO 
    FOREIGN KEY (SERVER_ID) REFERENCES TB_SERVER_INFO (SERVER_ID)
;


